### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by DengCong0126** [HongqingCao/GitDataV#12]
[root@test_server GitDataV]# npm run dev

> GitDataV@2.1.0 dev /opt/GitDataV
> vue-cli-service serve

/opt/GitDataV/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/GitDataV/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 3.10.0-957.12.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! GitDataV@2.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GitDataV@2.1.0 dev script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GitDataV package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GitDataV
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GitDataV
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/GitDataV/npm-debug.log

这是由于什么原因造成的

**Comment by HongqingCao** [comment]
请查看node版本是否太低，建议升级node版本

**Comment by DengCong0126** [comment]
[root@test_server ~]# node -v
v6.17.1
目前是该版本，是否能官网最新的v12.13.1呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"codercao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 下午5:40
收件人:&nbsp;"HongqingCao/GitDataV"<GitDataV@noreply.github.com&gt;;
抄送:&nbsp;"资料读取中，请稍后......"<824556110@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HongqingCao/GitDataV] 项目启动失败 (#12)




请查看node版本是否太低，建议升级node版本

**Comment by DengCong0126** [comment]
项目启动后的初始密码是什么，谢谢

**Comment by HongqingCao** [comment]
未设有初始密码，输入想要查看的github账号即可

**Comment by DengCong0126** [comment]
您好，我这边想把一个页面的不同二级页面放展示，所涉及和牵扯修改的内容多吗？本人是做运维的，目前会的东西不是太多，几个监控软件展示的都是不同功能，想请教一下。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"codercao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 上午9:57
收件人:&nbsp;"HongqingCao/GitDataV"<GitDataV@noreply.github.com&gt;;
抄送:&nbsp;"资料读取中，请稍后......"<824556110@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HongqingCao/GitDataV] 项目启动失败 (#12)




未设有初始密码，输入想要查看的github账号即可

**Comment by isxiaojian** [comment]
这个读的是github的仓库

**Comment by DengCong0126** [comment]
如果只展示指定的url内容，或者sql结果，需要改变的文件多吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jred"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午2:31
收件人:&nbsp;"HongqingCao/GitDataV"<GitDataV@noreply.github.com&gt;;
抄送:&nbsp;"资料读取中，请稍后......"<824556110@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HongqingCao/GitDataV] 项目启动失败 (#12)




这个读的是github的仓库
