### ISSUE TITLE
npm run dev 有问题

### ISSUE THREAD

**Issue by ocean-zhc** [HongqingCao/GitDataV#32]
[root@node3 GitDataV]#  npm run dev

> GitDataV@2.1.0 dev /opt/github/GitDataV
> vue-cli-service serve

/opt/github/GitDataV/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/github/GitDataV/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)
    at Module._compile (module.js:570:32)

npm ERR! Linux 3.10.0-957.21.3.el7.x86_64
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! GitDataV@2.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GitDataV@2.1.0 dev script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GitDataV package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GitDataV
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GitDataV
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/github/GitDataV/npm-debug.log

**Comment by ocean-zhc** [comment]
nodejs 版本切换成 v10.15.1 解决问题，一开始node 最新版本v16.0.0
