### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by aaronsuscb** [HongqingCao/GitDataV#6]
按如下方式安装：
1）npm install -g cnpm --registry=https://registry.npm.taobao.org
2）cnpm install
3) npm run dev
报如下错误

C:\dev\workshop\vue\GitDataV-master\node_modules\_open@6.4.0@open\index.js:29
                ...options
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\dev\workshop\vue\GitDataV-master\node_modules\_@vue_cli-shared-utils@3.9.0@@vue\cli-shared
-utils\lib\openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GitDataV@2.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GitDataV@2.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-08T14_29_39_933Z-debug.log

**Comment by HongqingCao** [comment]
直接npm install安装即可
